language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

#gradlew에 실행권한 설정
before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r second-springboot2-webservice *
  - mkdir -p deploy
  - mv second-springboot2-webservice.zip deploy/second-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: test-springboot2-webservice
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deploy: true

  - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
      secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
      bucket: test-springboot2-build # S3 버킷
      key: second-springboot2-webservice.zip # 빌드 파일을 압축해서 전달
      bundle_type: zip
      application: test-springboot2-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
      deployment_group: test-springboot2-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
      region: ap-northeast-2
      wait-until-deployed: true

#CI 실행 완료시 메일로 전달
notifications:
  email:
    recipients:
      - kswon12@naver.com